### ISSUE TITLE
fbr functionality in nvim with submodule broken

### ISSUE THREAD

**Issue by KaiHoewelmeyer-TomTom** [kaihowl/dotfiles#642] opened 2023-08-29 16:29 UTC
```
[Fzf-lua] Unable to access 'fugitive:///Users/.../.git/modules/...', removing 'cwd' option.
```

**Comment by kaihowl** [comment] 2023-09-10 17:24
Cannot reproduce on MBA.

**Comment by kaihowl** [comment] 2023-09-10 17:25
Also not reproducible on MBP.

**Comment by kaihowl** [comment] 2023-09-10 17:28
Also cannot reproduce with older fzf-lua version around the time of the report.
Closing.

**Closed by kaihowl** 2023-09-10 17:28 UTC
